# Generated by Django 4.0.4 on 2022-05-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_persona_altura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('idPersona', models.BigIntegerField()),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50))
            ],
        ),
    ]
